"""comedor

Revision ID: 01a937a27ab2
Revises: 988587b7f89b
Create Date: 2026-05-04 22:55:47.788424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '01a937a27ab2'
down_revision: Union[str, Sequence[str], None] = '988587b7f89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_comedor',
    sa.Column('IdAuditoria_Comedor', sa.Integer(), nullable=False),
    sa.Column('HoraApertura', sa.DateTime(), nullable=False),
    sa.Column('HoraCerrar', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('IdAuditoria_Comedor')
    )
    op.create_table('auditoria_mesas',
    sa.Column('IdAuditoria_Mesas', sa.Integer(), nullable=False),
    sa.Column('IdMesa', sa.Integer(), nullable=False),
    sa.Column('IdOrden', sa.Integer(), nullable=False),
    sa.Column('HoraEntrada', sa.DateTime(), nullable=False),
    sa.Column('HoraSalida', sa.DateTime()),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Mesas'),
    sa.UniqueConstraint('IdOrden')
    )


    op.drop_column('pedidos', 'Fecha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('facturasordenes')
    op.drop_table('auditoria_mesas')
    op.drop_table('auditoria_comedor')
    # ### end Alembic commands ###
