"""alacienputa david

Revision ID: 197d371500cb
Revises: 231f45759fa2
Create Date: 2026-06-13 00:24:47.703862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197d371500cb'
down_revision: Union[str, Sequence[str], None] = '231f45759fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platilloseingredientes',
    sa.Column('IdRelacion', sa.Integer(), nullable=False),
    sa.Column('IdPlatillo', sa.Integer(), nullable=True),
    sa.Column('IdIngrediente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdIngrediente'], ['ingredientes.IdIngrediente'], ),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdRelacion')
    )
    op.drop_table('platillosingredientes')
    op.alter_column('pago', 'MetodoPagos',
               existing_type=sa.VARCHAR(length=15, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pago', 'MetodoPagos',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
    op.create_table('platillosingredientes',
    sa.Column('IdPlatillo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IdIngrediente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IdIngrediente'], ['ingredientes.IdIngrediente'], name=op.f('FK__platillos__IdIng__0A9D95DB')),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], name=op.f('FK__platillos__IdPla__0B91BA14')),
    sa.PrimaryKeyConstraint('IdPlatillo', 'IdIngrediente', name=op.f('PK__platillo__D4BBEACE59D21C3F'))
    )
    op.drop_table('platilloseingredientes')
    # ### end Alembic commands ###
