"""mas auditoria caja

Revision ID: 231f45759fa2
Revises: bc060befdd19
Create Date: 2026-06-04 00:21:57.706658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '231f45759fa2'
down_revision: Union[str, Sequence[str], None] = 'bc060befdd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_transaciones',
    sa.Column('IdAuditoria_Transaciones', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdPago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdPago'], ['pago.IdPago'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Transaciones')
    )
    op.create_index(op.f('ix_auditoria_transaciones_IdAuditoria_Transaciones'), 'auditoria_transaciones', ['IdAuditoria_Transaciones'], unique=False)
    op.alter_column('pago', 'MetodoPagos',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.Enum('TRANSFERENCIA', 'EFECTIVO', 'TARJETA_CREDITO', 'TARJETA_DEBITO', name='tipopago'),
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pago', 'MetodoPagos',
               existing_type=sa.Enum('TRANSFERENCIA', 'EFECTIVO', 'TARJETA_CREDITO', 'TARJETA_DEBITO', name='tipopago'),
               type_=sa.VARCHAR(length=13, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    op.drop_index(op.f('ix_auditoria_transaciones_IdAuditoria_Transaciones'), table_name='auditoria_transaciones')
    op.drop_table('auditoria_transaciones')
    # ### end Alembic commands ###
