"""Modificar tablas de cliente, facturas y ordenes

Revision ID: 429f53ff53a8
Revises: f24d52ce2c5f
Create Date: 2026-03-18 21:34:02.090642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '429f53ff53a8'
down_revision: Union[str, Sequence[str], None] = 'f24d52ce2c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.batch_alter_table('metodospagoordenes','pago')
    op.batch_alter_table('facturaspedidos', 'facturas')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodospago',
    sa.Column('IdMetodoPago', sa.Integer(), nullable=False),
    sa.Column('NombreTipo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('IdMetodoPago')
    )
    op.create_table('clientedireccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('Dirreccion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('IdPago', sa.Integer(), nullable=False),
    sa.Column('IdMetodoPagos', sa.Integer(), nullable=True),
    sa.Column('IdOrden', sa.Integer(), nullable=True),
    sa.Column('PagoTotal', sa.Numeric(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['IdMetodoPagos'], ['metodospago.IdMetodoPago'], ),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdPago')
    )
    op.create_index(op.f('ix_pago_IdPago'), 'pago', ['IdPago'], unique=False)





    op.drop_index(op.f('ix_pagoordenes_IdPagoOrdenes'), table_name='pagoordenes')
    op.drop_table('pagoordenes')
    op.add_column('facturas', sa.Column('IdOrdenes', sa.Integer(), nullable=True))
    op.alter_column('facturas', 'Fecha',
               existing_type=sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'facturas', 'ordenes', ['IdOrdenes'], ['IdOrdenes'])
    op.add_column('pedidos', sa.Column('IdOrdenes', sa.Integer(), nullable=True))
    op.alter_column('pedidos', 'Fecha',
               existing_type=sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('FK__pedidos__IdClien__15DA3E5D', 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'ordenes', ['IdOrdenes'], ['IdOrdenes'])
    op.drop_column('pedidos', 'IdCliente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('IdCliente', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('FK__pedidos__IdClien__6C190EBB'), 'pedidos', 'clientes', ['IdCliente'], ['IdCliente'])
    op.alter_column('pedidos', 'Fecha',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.drop_column('pedidos', 'IdOrdenes')
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.alter_column('facturas', 'Fecha',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.drop_column('facturas', 'IdOrdenes')
    op.create_table('pagoordenes',
    sa.Column('IdPagoOrdenes', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('IdMetodoPagoOrdenes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IdOrden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PagoTotal', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=False),
    sa.Column('Fecha', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IdMetodoPagoOrdenes'], ['metodospagoordenes.IdMetodoPagoOrdenes'], name=op.f('FK__pagoorden__IdMet__7E02B4CC')),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], name=op.f('FK__pagoorden__IdOrd__7EF6D905')),
    sa.PrimaryKeyConstraint('IdPagoOrdenes', name=op.f('PK__pagoorde__6ABD25BADEB75860'))
    )
    op.create_index(op.f('ix_pagoordenes_IdPagoOrdenes'), 'pagoordenes', ['IdPagoOrdenes'], unique=False)
    op.create_table('facturasordenes',
    sa.Column('IdFactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IdOrdenes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['IdFactura'], ['facturas.IdFactura'], name=op.f('FK__facturaso__IdFac__7A3223E8')),
    sa.ForeignKeyConstraint(['IdOrdenes'], ['ordenes.IdOrdenes'], name=op.f('FK__facturaso__IdOrd__7B264821')),
    sa.PrimaryKeyConstraint('IdFactura', name=op.f('PK__facturas__50E7BAF11E7E593C'))
    )
    op.create_table('facturaspedidos',
    sa.Column('IdFactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IdPedido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IdFactura'], ['facturas.IdFactura'], name=op.f('FK__facturasp__IdFac__01142BA1')),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], name=op.f('FK__facturasp__IdPed__02084FDA')),
    sa.PrimaryKeyConstraint('IdFactura', name=op.f('PK__facturas__50E7BAF1D2403F5B'))
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61D8D6F870'))
    )
    op.create_table('detallesdepedidos',
    sa.Column('IdDetalle', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('IdPedido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IdPlatillo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PrecioUnitario', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], name=op.f('FK__detallesd__IdPed__75A278F5')),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], name=op.f('FK__detallesd__IdPla__76969D2E')),
    sa.PrimaryKeyConstraint('IdDetalle', name=op.f('PK__detalles__E43646A55DB0570E'))
    )
    op.create_table('metodospagoordenes',
    sa.Column('IdMetodoPagoOrdenes', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('NombreTipo', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('IdMetodoPagoOrdenes', name=op.f('PK__metodosp__F1137B7821D1FD04'))
    )
    op.drop_index(op.f('ix_pago_IdPago'), table_name='pago')
    op.drop_table('pago')
    op.drop_table('clientedireccion')
    op.drop_table('metodospago')
    # ### end Alembic commands ###
