"""auditorias 

Revision ID: 50dd49ca9fa3
Revises: fc6e41b08995
Create Date: 2026-05-26 16:51:10.775876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '50dd49ca9fa3'
down_revision: Union[str, Sequence[str], None] = 'fc6e41b08995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('auditoria_pedidos', sa.Column('IdPedido', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('FK__auditoria__IdOrd__10E07F16'), 'auditoria_pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'auditoria_pedidos', 'pedidos', ['IdPedido'], ['IdPedido'])
    op.drop_column('auditoria_pedidos', 'IdOrden')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.add_column('auditoria_pedidos', sa.Column('IdOrden', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auditoria_pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('FK__auditoria__IdOrd__10E07F16'), 'auditoria_pedidos', 'ordenes', ['IdOrden'], ['IdOrdenes'])
    op.drop_column('auditoria_pedidos', 'IdPedido')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6195AB0B6F'))
    )
    # ### end Alembic commands ###
