"""agregar correo usuario

Revision ID: 6d0a998e2a5b
Revises: 0bcff2925cd9
Create Date: 2026-10-01 21:20:37.075009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d0a998e2a5b'
down_revision: Union[str, Sequence[str], None] = '0bcff2925cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=350), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'correo')
    # ### end Alembic commands ###
