"""unique pedidos

Revision ID: 97358b6d16b8
Revises: 50dd49ca9fa3
Create Date: 2026-06-02 06:19:17.719987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '97358b6d16b8'
down_revision: Union[str, Sequence[str], None] = '50dd49ca9fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoriaimagenes',
    sa.Column('IDAU_imagenes', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('accion', sa.Enum('CREADO', 'ELIMINAR', 'MODIFICAR', name='accionimagenes'), nullable=False),
    sa.PrimaryKeyConstraint('IDAU_imagenes')
    )
    op.create_unique_constraint(
        'uq_pedidosordenes_idordenes', 
        'pedidosordenes', 
        ['IdOrdenes']
    )
    op.drop_table('sysdiagrams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B616D7931C5'))
    )
    op.drop_table('auditoriaimagenes')
    op.drop_constraint('uq_pedidosordenes_idordenes', 'pedidosordenes', type_='unique')
    # ### end Alembic commands ###
