"""RELACION facturas ordenes

Revision ID: 988587b7f89b
Revises: e0cf940b7493
Create Date: 2026-04-28 00:22:57.773403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988587b7f89b'
down_revision: Union[str, Sequence[str], None] = 'e0cf940b7493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FacturasOrdenes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdFactura', sa.Integer(), nullable=False),
    sa.Column('IdOrdenes', sa.Integer(), nullable=False, unique=True),
    sa.ForeignKeyConstraint(['IdFactura'], ['facturas.IdFactura'], ),
    sa.ForeignKeyConstraint(['IdOrdenes'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_constraint(op.f('FK__facturas__IdOrde__03F0984C'), 'facturas', type_='foreignkey')
    op.drop_column('facturas', 'IdOrdenes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('IdOrdenes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__facturas__IdOrde__03F0984C'), 'facturas', 'ordenes', ['IdOrdenes'], ['IdOrdenes'])
    op.drop_table('facturaspedidos')
    # ### end Alembic commands ###
