"""agregar imagenes en la bd

Revision ID: 9c1a538b7431
Revises: 01a937a27ab2
Create Date: 2026-05-08 21:14:36.679519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9c1a538b7431'
down_revision: Union[str, Sequence[str], None] = '01a937a27ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoriaimagenes',
    sa.Column('IDAU_imagenes', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('accion', sa.Enum('CREADO', 'ELIMINAR', 'MODIFICAR', name='accionimagenes'), nullable=False),
    sa.PrimaryKeyConstraint('IDAU_imagenes')
    )
    op.create_table('imagenesplatillos',
    sa.Column('IdImagen', sa.Integer(), nullable=False),
    sa.Column('UrlImagen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdPlatillo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdImagen')
    )
    op.create_index(op.f('ix_imagenesplatillos_IdImagen'), 'imagenesplatillos', ['IdImagen'], unique=False)
    op.alter_column('auditoria_mesas', 'HoraSalida',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditoria_mesas', 'HoraSalida',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6187F10D58'))
    )
    op.drop_index(op.f('ix_imagenesplatillos_IdImagen'), table_name='imagenesplatillos')
    op.drop_table('imagenesplatillos')
    op.drop_table('auditoriaimagenes')
    # ### end Alembic commands ###
