"""caja

Revision ID: bc060befdd19
Revises: 4f6032df4fa4
Create Date: 2026-06-03 23:14:50.573010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bc060befdd19'
down_revision: Union[str, Sequence[str], None] = '4f6032df4fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reembolsos',
    sa.Column('IdReembolso', sa.Integer(), nullable=False),
    sa.Column('IdOrden', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Numeric(), nullable=False),
    sa.Column('Razones', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdReembolso')
    )
    
    op.create_table('referenciapago',
    sa.Column('IdReferenciaPago', sa.Integer(), nullable=False),
    sa.Column('IdPago', sa.Integer(), nullable=True),
    sa.Column('referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['IdPago'], ['pago.IdPago'], ),
    sa.PrimaryKeyConstraint('IdReferenciaPago')
    )
    
    op.drop_constraint(op.f('FK__pago__IdMetodoPa__07C12930'), 'pago', type_='foreignkey')
    op.drop_column('pago', 'IdMetodoPagos')
    op.drop_table('metodospago')
    
    # CORRECCIÓN AQUÍ: Se define como sa.String(length=50) para evitar el error de truncamiento.
    # La validación de que sea 'EFECTIVO' o 'TARJETA_CREDITO' la seguirá haciendo FastAPI.
    op.add_column('pago', sa.Column('MetodoPagos', sa.String(length=50), nullable=True))
    
    op.add_column('pago', sa.Column('Estado', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('IdMetodoPagos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__pago__IdMetodoPa__07C12930'), 'pago', 'metodospago', ['IdMetodoPagos'], ['IdMetodoPago'])
    op.drop_column('pago', 'Estado')
    op.drop_column('pago', 'MetodoPagos')
    
    op.create_table('metodospago',
    sa.Column('IdMetodoPago', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('NombreTipo', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('IdMetodoPago', name=op.f('PK__metodosp__6F49A9BE736135B6'))
    )
    
    op.drop_table('referenciapago')
    op.drop_table('reembolsos')
    # ### end Alembic commands ###