"""agregar tipo pedidos

Revision ID: c6a8ce2ddef4
Revises: fbb34492c916
Create Date: 2026-05-14 22:36:47.906605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'c6a8ce2ddef4'
down_revision: Union[str, Sequence[str], None] = 'fbb34492c916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipopedido',
    sa.Column('IdTipoPedido', sa.Integer(), nullable=False),
    sa.Column('IdPedido', sa.Integer(), nullable=False),
    sa.Column('TipoPedidos', sa.Enum('EVENTO', 'CONTRATO', name='tipopedido'), nullable=False),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], ),
    sa.PrimaryKeyConstraint('IdTipoPedido'),
    sa.UniqueConstraint('IdPedido')
    )
    op.drop_table('sysdiagrams')
    op.alter_column('pedidos', 'fecha',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'fecha',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6187F10D58'))
    )
    op.drop_table('tipopedido')
    # ### end Alembic commands ###
