"""agregar tipo pedidos ahora si

Revision ID: c92d23836ca7
Revises: c6a8ce2ddef4
Create Date: 2026-05-17 20:51:30.205989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92d23836ca7'
down_revision: Union[str, Sequence[str], None] = 'c6a8ce2ddef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipopedido')
    op.add_column('pedidos', sa.Column('TipoPedidos', sa.Enum('EVENTO', 'CONTRATO', 'BUFFET', name='tipopedidoss'), server_default='EVENTO', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'TipoPedidos')
    op.create_table('tipopedido',
    sa.Column('IdTipoPedido', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('IdPedido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TipoPedidos', sa.VARCHAR(length=8, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], name=op.f('FK__tipopedid__IdPed__42ACE4D4')),
    sa.PrimaryKeyConstraint('IdTipoPedido', name=op.f('PK__tipopedi__4B4A789535E3C8DD'))
    )
    # ### end Alembic commands ###
