"""ESTADO DE LAS ORDENES

Revision ID: e0cf940b7493
Revises: b5e5dc1f6eed
Create Date: 2026-04-25 22:21:30.162852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e0cf940b7493'
down_revision: Union[str, Sequence[str], None] = 'b5e5dc1f6eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metodospagoordenes')
    op.drop_table('sysdiagrams')
    op.drop_table('AuditoriaActualizacionPrecios')
    op.add_column('ordenes', sa.Column('Estado', sa.Enum('PENDIENTE', 'ENTREGADO', 'PAGADO', name='estadoorden'), nullable=False, server_default='PENDIENTE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes', 'Estado')
    op.create_table('AuditoriaActualizacionPrecios',
    sa.Column('IdOrden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IdPlatillo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PrecioAnterior', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('PrecioActualizado', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('Fecha', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Descripcion', sa.NVARCHAR(length=1000, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], name=op.f('FK__Auditoria__IdOrd__56E8E7AB')),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], name=op.f('FK__Auditoria__IdPla__57DD0BE4'))
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61E5CDF174'))
    )
    op.create_table('metodospagoordenes',
    sa.Column('IdMetodoPagoOrdenes', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('NombreTipo', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('IdMetodoPagoOrdenes', name=op.f('PK__metodosp__F1137B7823E4F175'))
    )
    # ### end Alembic commands ###
