"""agregar tablas de Ordenes ahora si xd

Revision ID: f24d52ce2c5f
Revises: 0f4c1f1f56a0
Create Date: 2026-03-15 00:54:47.844369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'f24d52ce2c5f'
down_revision: Union[str, Sequence[str], None] = '0f4c1f1f56a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodospagoordenes',
    sa.Column('IdMetodoPagoOrdenes', sa.Integer(), nullable=False),
    sa.Column('NombreTipo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('IdMetodoPagoOrdenes')
    )
    op.create_table('ordenes',
    sa.Column('IdOrdenes', sa.Integer(), nullable=False),
    sa.Column('CostoTotal', sa.Numeric(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('IdOrdenes')
    )
    op.create_index(op.f('ix_ordenes_IdOrdenes'), 'ordenes', ['IdOrdenes'], unique=False)
    op.create_table('detallesordenes',
    sa.Column('IdDetallesOrdenes', sa.Integer(), nullable=False),
    sa.Column('IdOrdenes', sa.Integer(), nullable=True),
    sa.Column('IdPlatillo', sa.Integer(), nullable=True),
    sa.Column('CantidadPlatillo', sa.Integer(), nullable=False),
    sa.Column('PrecioUnico', sa.Numeric(), nullable=False),
    sa.Column('CostoTotal', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['IdOrdenes'], ['ordenes.IdOrdenes'], ),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdDetallesOrdenes')
    )
    op.create_index(op.f('ix_detallesordenes_IdDetallesOrdenes'), 'detallesordenes', ['IdDetallesOrdenes'], unique=False)
    op.create_table('facturasordenes',
    sa.Column('IdFactura', sa.Integer(), nullable=False),
    sa.Column('IdOrdenes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdFactura'], ['facturas.IdFactura'], ),
    sa.ForeignKeyConstraint(['IdOrdenes'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdFactura')
    )
    op.create_table('pagoordenes',
    sa.Column('IdPagoOrdenes', sa.Integer(), nullable=False),
    sa.Column('IdMetodoPagoOrdenes', sa.Integer(), nullable=True),
    sa.Column('IdOrden', sa.Integer(), nullable=True),
    sa.Column('PagoTotal', sa.Numeric(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['IdMetodoPagoOrdenes'], ['metodospagoordenes.IdMetodoPagoOrdenes'], ),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdPagoOrdenes')
    )
    op.create_index(op.f('ix_pagoordenes_IdPagoOrdenes'), 'pagoordenes', ['IdPagoOrdenes'], unique=False)
    op.alter_column('categoriasinsumos', 'NombreCategoriaInsumo',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=150),
               existing_nullable=False)
    # Instrucción correcta para renombrar
    op.alter_column('facturas', 'FechaFactura', new_column_name='Fecha')
    op.alter_column('insumos', 'NombreInsumo',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=200),
               existing_nullable=False)
    op.alter_column('menudiario', 'FechaMenu', new_column_name='Fecha')
    op.alter_column('pedidos', 'FechaPedido', new_column_name='Fecha')
    op.alter_column('proveedores', 'NombreProveedor',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proveedores', 'NombreProveedor',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=150),
               type_=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.add_column('pedidos', sa.Column('FechaPedido', sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('pedidos', 'Fecha')
    op.add_column('menudiario', sa.Column('FechaMenu', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('menudiario', 'Fecha')
    op.alter_column('insumos', 'NombreInsumo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
               type_=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.add_column('facturas', sa.Column('FechaFactura', sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('facturas', 'Fecha')
    op.alter_column('categoriasinsumos', 'NombreCategoriaInsumo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=150),
               type_=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B617F7DB2A3'))
    )
    op.drop_index(op.f('ix_pagoordenes_IdPagoOrdenes'), table_name='pagoordenes')
    op.drop_table('pagoordenes')
    op.drop_table('facturasordenes')
    op.drop_index(op.f('ix_detallesordenes_IdDetallesOrdenes'), table_name='detallesordenes')
    op.drop_table('detallesordenes')
    op.drop_index(op.f('ix_ordenes_IdOrdenes'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_table('metodospagoordenes')
    # ### end Alembic commands ###
