"""init

Revision ID: f693fee5f1b8
Revises: 
Create Date: 2025-11-30 20:40:41.787745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'f693fee5f1b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogoplatillos',
    sa.Column('IdCatalogoPlatillo', sa.Integer(), nullable=False),
    sa.Column('NombreCatalogoPlatillo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('IdCatalogoPlatillo')
    )
    op.create_table('categoriasinsumos',
    sa.Column('IdCategoriaInsumo', sa.Integer(), nullable=False),
    sa.Column('NombreCategoriaInsumo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('IdCategoriaInsumo')
    )
    op.create_table('clientes',
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('NombreCliente', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('DireccionCliente', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.PrimaryKeyConstraint('IdCliente')
    )
    op.create_table('facturas',
    sa.Column('IdFactura', sa.Integer(), nullable=False),
    sa.Column('MontoTotal', sa.Numeric(), nullable=False),
    sa.Column('FechaFactura', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('CantidadTotal', sa.Integer(), nullable=False),
    sa.Column('Estado', sa.Enum('GENERADA', 'ENVIADA', 'ACEPTADA', 'PAGADA', 'ATRASADA', 'RECHAZADA', 'ANULADA', name='estadofactura'), nullable=False),
    sa.PrimaryKeyConstraint('IdFactura')
    )
    op.create_table('ingredientes',
    sa.Column('IdIngrediente', sa.Integer(), nullable=False),
    sa.Column('NombreIngrediente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('StockIngredientes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('IdIngrediente')
    )
    op.create_table('platillos',
    sa.Column('IdPlatillo', sa.Integer(), nullable=False),
    sa.Column('NombrePlatillo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('IdPlatillo')
    )
    op.create_table('proveedores',
    sa.Column('IdProveedor', sa.Integer(), nullable=False),
    sa.Column('NombreProveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Tipo', sa.Enum('ESPORANEO', 'FIJO', name='tipodeproveedor'), nullable=False),
    sa.PrimaryKeyConstraint('IdProveedor')
    )
    op.create_table('categoriaplatillos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IdPlatillo', sa.Integer(), nullable=True),
    sa.Column('IdCatalogoPlatillo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdCatalogoPlatillo'], ['catalogoplatillos.IdCatalogoPlatillo'], ),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_categoriaplatillos_IdCatalogoPlatillo'), 'categoriaplatillos', ['IdCatalogoPlatillo'], unique=False)
    op.create_table('clientecorreo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('CorreoElectronico', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientetelefono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('Telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('IdContrato', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('Presupuesto', sa.Float(), nullable=False),
    sa.Column('NumeroContrato', sa.Integer(), nullable=False),
    sa.Column('Estado', sa.Enum('ACTIVO', 'INACTIVO', 'PENDIENTE', name='estadocontrato'), nullable=False),
    sa.Column('FechaInicio', sa.DateTime(), nullable=False),
    sa.Column('FechaVencimiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('IdContrato')
    )
    op.create_table('insumos',
    sa.Column('IdInsumo', sa.Integer(), nullable=False),
    sa.Column('IdCategoriaInsumo', sa.Integer(), nullable=True),
    sa.Column('NombreInsumo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Prioridad', sa.Enum('ALTA', 'MEDIA', 'BAJA', name='prioridadinsumo'), nullable=False),
    sa.ForeignKeyConstraint(['IdCategoriaInsumo'], ['categoriasinsumos.IdCategoriaInsumo'], ),
    sa.PrimaryKeyConstraint('IdInsumo')
    )
    op.create_table('menudiario',
    sa.Column('IdMenu', sa.Integer(), nullable=False),
    sa.Column('IdPlatillo', sa.Integer(), ),
    sa.Column('FechaMenu', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdMenu')
    )
    op.create_index(op.f('ix_menudiario_IdPlatillo'), 'menudiario', ['IdPlatillo'], unique=False)
    op.create_table('pedidos',
    sa.Column('IdPedido', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('FechaPedido', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('Estado', sa.Enum('PENDIENTE', 'ENTREGADO', 'ANULADO', name='estadopedido'), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('IdPedido')
    )
    op.create_table('platillosingredientes',
    sa.Column('IdPlatillo', sa.Integer(), nullable=False),
    sa.Column('IdIngrediente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdIngrediente'], ['ingredientes.IdIngrediente'], ),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdPlatillo', 'IdIngrediente')
    )
    op.create_table('registrodeabastecimiento',
    sa.Column('IdRegistro', sa.Integer(), nullable=False),
    sa.Column('TotalIngresado', sa.Integer(), nullable=False),
    sa.Column('IdProveedor', sa.Integer(), nullable=True),
    sa.Column('CostoTotal', sa.Numeric(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['IdProveedor'], ['proveedores.IdProveedor'], ),
    sa.PrimaryKeyConstraint('IdRegistro')
    )
    op.create_table('detallesdepedidos',
    sa.Column('IdDetalle', sa.Integer(), nullable=False),
    sa.Column('IdPedido', sa.Integer(), nullable=False),
    sa.Column('IdPlatillo', sa.Integer(), nullable=False),
    sa.Column('Cantidad', sa.Integer(), nullable=False),
    sa.Column('PrecioUnitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], ),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdDetalle')
    )
    op.create_table('detallesregistroingredientes',
    sa.Column('IdRegistroAbastecimiento', sa.Integer(), nullable=False),
    sa.Column('IdIngrediente', sa.Integer(), nullable=False),
    sa.Column('TotalIngresado', sa.Integer(), nullable=False),
    sa.Column('CostoIndividual', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['IdIngrediente'], ['ingredientes.IdIngrediente'], ),
    sa.ForeignKeyConstraint(['IdRegistroAbastecimiento'], ['registrodeabastecimiento.IdRegistro'], ),
    sa.PrimaryKeyConstraint('IdRegistroAbastecimiento', 'IdIngrediente')
    )
    op.create_table('detallesregistroinsumos',
    sa.Column('IdRegistroAbastecimiento', sa.Integer(), nullable=False),
    sa.Column('IdInsumo', sa.Integer(), nullable=False),
    sa.Column('TotalIngresado', sa.Integer(), nullable=False),
    sa.Column('CostoIndividual', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['IdInsumo'], ['insumos.IdInsumo'], ),
    sa.ForeignKeyConstraint(['IdRegistroAbastecimiento'], ['registrodeabastecimiento.IdRegistro'], ),
    sa.PrimaryKeyConstraint('IdRegistroAbastecimiento', 'IdInsumo')
    )
    op.create_table('facturaspedidos',
    sa.Column('IdFactura', sa.Integer(), nullable=False),
    sa.Column('IdPedido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdFactura'], ['facturas.IdFactura'], ),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], ),
    sa.PrimaryKeyConstraint('IdFactura')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturaspedidos')
    op.drop_table('detallesregistroinsumos')
    op.drop_table('detallesregistroingredientes')
    op.drop_table('detallesdepedidos')
    op.drop_table('registrodeabastecimiento')
    op.drop_table('platillosingredientes')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_menudiario_IdPlatillo'), table_name='menudiario')
    op.drop_table('menudiario')
    op.drop_table('insumos')
    op.drop_table('contrato')
    op.drop_table('clientetelefono')
    op.drop_table('clientecorreo')
    op.drop_index(op.f('ix_categoriaplatillos_IdCatalogoPlatillo'), table_name='categoriaplatillos')
    op.drop_table('categoriaplatillos')
    op.drop_table('proveedores')
    op.drop_table('platillos')
    op.drop_table('ingredientes')
    op.drop_table('facturas')
    op.drop_table('clientes')
    op.drop_table('categoriasinsumos')
    op.drop_table('catalogoplatillos')
    # ### end Alembic commands ###
