"""agregar relacion pedidos ordenes

Revision ID: fbb34492c916
Revises: 9c1a538b7431
Create Date: 2026-05-12 15:19:52.387734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'fbb34492c916'
down_revision: Union[str, Sequence[str], None] = '9c1a538b7431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidosordenes',
    sa.Column('IdPedidosOrdenes', sa.Integer(), nullable=False),
    sa.Column('IdPedido', sa.Integer(), nullable=False),
    sa.Column('IdOrdenes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdOrdenes'], ['ordenes.IdOrdenes'], ),
    sa.ForeignKeyConstraint(['IdPedido'], ['pedidos.IdPedido'], ),
    sa.PrimaryKeyConstraint('IdPedidosOrdenes')
    )
    op.add_column('pedidos', sa.Column('fecha', sa.DateTime()))
    op.drop_constraint(op.f('FK__pedidos__IdOrden__09A971A2'), 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'IdOrdenes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('IdOrdenes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__pedidos__IdOrden__09A971A2'), 'pedidos', 'ordenes', ['IdOrdenes'], ['IdOrdenes'])
    op.drop_column('pedidos', 'fecha')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6187F10D58'))
    )
    op.drop_table('pedidosordenes')
    # ### end Alembic commands ###
