"""auditorias 

Revision ID: fc6e41b08995
Revises: d31708db4da9
Create Date: 2026-05-26 16:44:26.755767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fc6e41b08995'
down_revision: Union[str, Sequence[str], None] = 'd31708db4da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_imagenes',
    sa.Column('IdAuditoria_Imagenes', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdImagen', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.PrimaryKeyConstraint('IdAuditoria_Imagenes')
    )
    op.create_index(op.f('ix_auditoria_imagenes_IdAuditoria_Imagenes'), 'auditoria_imagenes', ['IdAuditoria_Imagenes'], unique=False)
    op.create_table('auditoria_cliente',
    sa.Column('IdAuditoria_Platillos', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['clientes.IdCliente'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Platillos')
    )
    op.create_index(op.f('ix_auditoria_cliente_IdAuditoria_Platillos'), 'auditoria_cliente', ['IdAuditoria_Platillos'], unique=False)
    op.create_table('auditoria_facturas',
    sa.Column('IdAuditoria_Facturas', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdFactura', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdFactura'], ['facturas.IdFactura'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Facturas')
    )
    op.create_index(op.f('ix_auditoria_facturas_IdAuditoria_Facturas'), 'auditoria_facturas', ['IdAuditoria_Facturas'], unique=False)
    op.create_table('auditoria_platillos',
    sa.Column('IdAuditoria_Platillos', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdPlatillo', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdPlatillo'], ['platillos.IdPlatillo'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Platillos')
    )
    op.create_index(op.f('ix_auditoria_platillos_IdAuditoria_Platillos'), 'auditoria_platillos', ['IdAuditoria_Platillos'], unique=False)
    op.create_table('auditoria_usuario',
    sa.Column('IdAuditoria_Usuario', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdUsuarioCreado', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdUsuarioCreado'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Usuario')
    )
    op.create_index(op.f('ix_auditoria_usuario_IdAuditoria_Usuario'), 'auditoria_usuario', ['IdAuditoria_Usuario'], unique=False)
    op.create_table('auditoria_ordenes',
    sa.Column('IdAuditoria_Facturas', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdOrden', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Facturas')
    )
    op.create_index(op.f('ix_auditoria_ordenes_IdAuditoria_Facturas'), 'auditoria_ordenes', ['IdAuditoria_Facturas'], unique=False)
    op.create_table('auditoria_pedidos',
    sa.Column('IdAuditoria_Facturas', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdOrden', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdOrden'], ['ordenes.IdOrdenes'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Facturas')
    )
    op.create_index(op.f('ix_auditoria_pedidos_IdAuditoria_Facturas'), 'auditoria_pedidos', ['IdAuditoria_Facturas'], unique=False)
    op.create_table('auditoria_pagos',
    sa.Column('IdAuditoria_Platillos', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IdPago', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('TipoAccion', sa.Enum('CREAR', 'ELIMINAR', 'ACTUALIZAR', 'MODIFICAR', name='tipodeaccion'), nullable=False),
    sa.ForeignKeyConstraint(['IdPago'], ['pago.IdPago'], ),
    sa.PrimaryKeyConstraint('IdAuditoria_Platillos')
    )
    op.create_index(op.f('ix_auditoria_pagos_IdAuditoria_Platillos'), 'auditoria_pagos', ['IdAuditoria_Platillos'], unique=False)
#     op.drop_table('sysdiagrams')
    op.add_column('auditoria_comedor', sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_auditoria_comedor_IdAuditoria_Comedor'), 'auditoria_comedor', ['IdAuditoria_Comedor'], unique=False)
    op.create_index(op.f('ix_auditoria_mesas_IdAuditoria_Mesas'), 'auditoria_mesas', ['IdAuditoria_Mesas'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_auditoria_mesas_IdAuditoria_Mesas'), table_name='auditoria_mesas')
    op.drop_index(op.f('ix_auditoria_comedor_IdAuditoria_Comedor'), table_name='auditoria_comedor')
    op.drop_column('auditoria_comedor', 'Username')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B618261669A'))
    )
    op.drop_index(op.f('ix_auditoria_pagos_IdAuditoria_Platillos'), table_name='auditoria_pagos')
    op.drop_table('auditoria_pagos')
    op.drop_index(op.f('ix_auditoria_pedidos_IdAuditoria_Facturas'), table_name='auditoria_pedidos')
    op.drop_table('auditoria_pedidos')
    op.drop_index(op.f('ix_auditoria_ordenes_IdAuditoria_Facturas'), table_name='auditoria_ordenes')
    op.drop_table('auditoria_ordenes')
    op.drop_index(op.f('ix_auditoria_usuario_IdAuditoria_Usuario'), table_name='auditoria_usuario')
    op.drop_table('auditoria_usuario')
    op.drop_index(op.f('ix_auditoria_platillos_IdAuditoria_Platillos'), table_name='auditoria_platillos')
    op.drop_table('auditoria_platillos')
    op.drop_index(op.f('ix_auditoria_facturas_IdAuditoria_Facturas'), table_name='auditoria_facturas')
    op.drop_table('auditoria_facturas')
    op.drop_index(op.f('ix_auditoria_cliente_IdAuditoria_Platillos'), table_name='auditoria_cliente')
    op.drop_table('auditoria_cliente')
    op.drop_index(op.f('ix_auditoria_imagenes_IdAuditoria_Imagenes'), table_name='auditoria_imagenes')
    op.drop_table('auditoria_imagenes')
    # ### end Alembic commands ###
