"""menu diario con hora

Revision ID: fdb8da1a0356
Revises: 197d371500cb
Create Date: 2026-06-16 23:39:08.524645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb8da1a0356'
down_revision: Union[str, Sequence[str], None] = '197d371500cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menudiario', sa.Column('Hora', sa.Time()))
    op.alter_column('menudiario', 'Fecha',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menudiario', 'Fecha',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.drop_column('menudiario', 'Hora')
    # ### end Alembic commands ###
