from .insumos import *
from .clientes import *
from .pedidos import *
from .platillos import *
from .facturas import *
from .ordenes import *
from .proveedores import *
from .comedor import *
from .imagenes import *
from .Usuarios import *