CREATE PROC MostrarDetalles
	@Id INT = NULL,
	@IdCliente INT = NULL
AS
BEGIN
	SET NOCOUNT ON

	IF @Id IS NULL AND @IdCliente IS NULL
	BEGIN
		PRINT('INGRESE ALMENOS UN IDENTIFICADOR')
		RETURN 1
	END

	SELECT C.NombreCliente, O.IdOrdenes, P.NombrePlatillo, OD.CantidadPlatillo, OD.PrecioUnico FROM ordenes O
	INNER JOIN detallesordenes OD ON O.IdOrdenes = OD.IdOrdenes
	INNER JOIN clientes C ON O.IdCliente = C.IdCliente
	INNER JOIN platillos P ON OD.IdPlatillo = P.IdPlatillo

	WHERE (@Id IS NULL OR O.IdOrdenes = @Id)
    AND
    (@IdCliente IS NULL OR O.IdCliente = @IdCliente)
	/* ESTE WHERE ES ESPECIAL, YA QUE PUEDE SER QUE UN SOLO MANDE EL ID DE LA ORDEN Y NO DEL CLIENTE 
	ENTONCES LA SENTENCIA 
		(@PARAM1 IS NULL OR COLUM = @PARAM1)
		SI ES NULL DEVUELVE TRUE, Y SE OMITE LA VALIDACION DE LA COLUMNA 
		SI NO ES NULL, VALIDA LA COLUMNA

		ENTONCES DE ESTA FORMA SE LOGRA VALIDA LA COLUMNA Y SE OMITE EL NULL
	*/
	ORDER BY C.NombreCliente

END